# Generated by Django 4.0.6 on 2023-06-09 04:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0003_remove_enddaydailyreport_beverage_sale_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='enddaydailyreport',
            name='cash',
        ),
        migrations.RemoveField(
            model_name='enddaydailyreport',
            name='complimentary',
        ),
        migrations.RemoveField(
            model_name='enddaydailyreport',
            name='credit',
        ),
        migrations.RemoveField(
            model_name='enddaydailyreport',
            name='credit_card',
        ),
        migrations.RemoveField(
            model_name='enddaydailyreport',
            name='end_bill',
        ),
        migrations.RemoveField(
            model_name='enddaydailyreport',
            name='mobile_payment',
        ),
        migrations.RemoveField(
            model_name='enddaydailyreport',
            name='start_bill',
        ),
        migrations.RemoveField(
            model_name='enddaydailyreport',
            name='terminal',
        ),
        migrations.RemoveField(
            model_name='enddaydailyreport',
            name='total_sale',
        ),
        migrations.AddField(
            model_name='enddaydailyreport',
            name='total_orders',
            field=models.IntegerField(default=0),
        ),
    ]
