# Generated by Django 4.0.6 on 2023-06-09 04:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0004_remove_enddaydailyreport_cash_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='enddaydailyreport',
            old_name='net_sales',
            new_name='net_amount',
        ),
        migrations.AddField(
            model_name='enddaydailyreport',
            name='total_amount',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
    ]
