# Generated by Django 4.0.6 on 2023-06-12 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_alter_order_agent'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='unique_order_id',
            field=models.CharField(default='a', max_length=50, unique=True),
            preserve_default=False,
        ),
    ]
