# Generated by Django 4.0.6 on 2023-06-12 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0003_order_unique_order_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='checked',
            field=models.BooleanField(default=False),
        ),
    ]
