# Generated by Django 4.0.6 on 2023-06-13 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0004_order_checked'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='bill_generated',
            field=models.BooleanField(default=False),
        ),
    ]
